language: java
jdk:
  - openjdk8
  - openjdk11
  - oraclejdk8
install: /bin/true
script: mvn install --quiet && cd sdk2refactor && mvn install --quiet
after_success:
  # https://docs.codecov.io/docs/about-the-codecov-bash-uploader
  - bash <(curl -s https://codecov.io/bash)
